"""create findings table

Revision ID: 35aa2ed5c172
Revises: b7d4e1f0a2c3
Create Date: 2026-07-09 23:52:14.996105

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '35aa2ed5c172'
down_revision: str | None = 'b7d4e1f0a2c3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('findings',
    sa.Column('doc_id', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('comment_id', sa.String(), nullable=True),
    sa.Column('original_text', sa.String(), nullable=False),
    sa.Column('proposed_change', sa.String(), nullable=False),
    sa.Column('reason_de', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('doc_id', 'key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('findings')
    # ### end Alembic commands ###
