"""create review_runs table

Revision ID: af4a1be91c55
Revises:
Create Date: 2026-06-13 15:47:52.413706

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "af4a1be91c55"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "review_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("doc_id", sa.String(), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finding_count", sa.Integer(), nullable=False),
        sa.Column("correlation_id", sa.String(), nullable=False),
        sa.Column("posted_finding_keys", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("token_budget", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("review_runs")
    # ### end Alembic commands ###
