"""add output_doc_id to review_runs

Revision ID: b600dfe686c5
Revises: af4a1be91c55
Create Date: 2026-07-21 23:01:03.324240

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "b600dfe686c5"
down_revision: str | None = "af4a1be91c55"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("review_runs", sa.Column("output_doc_id", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("review_runs", "output_doc_id")
    # ### end Alembic commands ###
