from typing import Protocol
from uuid import UUID

from pagedoctor.domain.models.doc_state import DocReviewState
from pagedoctor.domain.models.run import ReviewRun


class RunRepositoryPort(Protocol):
    def save(self, run: ReviewRun) -> None: ...
    def get(self, run_id: UUID) -> ReviewRun: ...
    def list_recent(self, limit: int = 50) -> list[ReviewRun]: ...
    def get_doc_state(self, doc_id: str) -> DocReviewState | None: ...
    def save_doc_state(self, state: DocReviewState) -> None: ...
