from typing import Protocol
from uuid import UUID

from pagedoctor.domain.models.run import ReviewRun


class RunRepositoryPort(Protocol):
    def save(self, run: ReviewRun) -> None: ...
    def get(self, run_id: UUID) -> ReviewRun: ...
    def list_recent(self, limit: int = 50) -> list[ReviewRun]: ...
    def list_for_doc(self, doc_id: str, limit: int = 20) -> list[ReviewRun]: ...
